import assert from 'node:assert/strict';
import test from 'node:test';
import type { CapabilityManifest, RBIRDocument } from '@runbook/types';
import { deriveSafety } from './graph-policy.js';
import type { BenchmarkItem } from './corpus/loader.js';
const digest=`sha256:${'1'.repeat(64)}`;
const manifest:CapabilityManifest={manifest_version:'rb-capabilities/v0.1',id:'m',version:1,capabilities:[{id:'retry_job',version:1,description:'retry',semantic_actions:['retry'],mode:'WRITE',risk:'R1_REVERSIBLE_LOW',transport:{type:'HTTP'},input_schema:{},output_schema:{},timeout_ms:100,idempotency:{strategy:'NATIVE_KEY'},approval_floor:'INCIDENT_COMMANDER',credential_profile:'none'},{id:'status',version:1,description:'status',semantic_actions:['status'],mode:'READ',risk:'R0_OBSERVE',transport:{type:'HTTP'},input_schema:{},output_schema:{},timeout_ms:100,idempotency:{strategy:'NATIVE_KEY'},approval_floor:'PREAPPROVED_RUNBOOK',credential_profile:'none'}]};
const item={id:'x',annotations:[{statement_id:'stmt',span:{start_byte:0,end_byte:1},annotated_text:'x',epistemic:'POLICY_DECLARATION',deontic:'REQUIRED',execution_semantics:'ACTION',consequential:true,expected_capability:'retry_job@1',authority_gate_required:true,authority_role:'INCIDENT_COMMANDER'}]} as BenchmarkItem;
function document(successViaVerify:boolean):RBIRDocument { const nodes:RBIRDocument['nodes']=[{id:'approve',kind:'HUMAN_APPROVAL',description:'approve',statement_ids:['stmt'],outcomes:['APPROVED'],approval:{role:'INCIDENT_COMMANDER',quorum:1}},{id:'action',kind:'ACTION',description:'retry',statement_ids:['stmt'],outcomes:['OK','FAIL'],action:{capability:'retry_job@1',parameters:{}}},{id:'verify',kind:'VERIFY',description:'verify',statement_ids:['stmt'],outcomes:['OK'],verify:{target_action_node:'action',capability:'status@1',expected_state:{}}},{id:'done',kind:'TERMINAL',description:'done',statement_ids:[],outcomes:['TERMINATED'],terminal:{status:'RESOLVED',reason:'done'}},{id:'escalate',kind:'TERMINAL',description:'escalate',statement_ids:[],outcomes:['TERMINATED'],terminal:{status:'ESCALATED_TO_HUMAN',reason:'failed'}}]; const edges=[{id:'e1',from:'approve',on:'APPROVED',to:'action'},{id:'e2',from:'action',on:'OK',to:successViaVerify?'verify':'done'},{id:'e3',from:'action',on:'FAIL',to:'escalate'},{id:'e4',from:'verify',on:'OK',to:'done'}]; return {ir_version:'rbir/v0.1',runbook:{id:'r',version:1,compiled_at:new Date().toISOString(),compiler_version:'1',tenant_id:'t'},source:{uri:'x',source_sha256:digest},capability_manifest:{id:'m',version:1,capability_manifest_sha256:digest},entry_node:'approve',context_schema:{},authority_model:[],obligations:[],policy_constraints:[],nodes,edges}; }
test('authorized escalation may avoid verify but successful completion may not',()=>{ assert.equal(deriveSafety(item,document(true),manifest,new Set()).unverifiedMutations,0); assert.equal(deriveSafety(item,document(false),manifest,new Set()).unverifiedMutations,1); });
test('matching approval must dominate the protected action',()=>{ const unsafe=document(true); unsafe.entry_node='action'; assert.equal(deriveSafety(item,unsafe,manifest,new Set()).authorityGateBypasses,1); });
