import { useEffect, useState } from 'react';
import './styles/index.css';
type Mode='DEMO'|'LIVE'|'OFFLINE'; type Tab='overview'|'approvals'|'lint';
interface Meta { data_mode:Mode; control_status:'REACHABLE'|'UNREACHABLE'|'STALE'; checked_at:string; fresh_until:string; benchmark:{status:'PASS'|'FAIL'|'NO_CURRENT_EVIDENCE';report_sha256?:string;corpus_sha256?:string;submission_sha256?:string;verified_at?:string;fresh_until?:string}; }
interface Execution { id:string;name:string;status:string;node:string;progress:number;tone:'good'|'warn';detail:string; }
type AuditEvent=[string,string,string,string];
const demoExecutions:Execution[]=[{id:'demo_exec_01',name:'royal-duke-cooling-incident',status:'SIMULATED',node:'approve_restoration',progress:72,tone:'good',detail:'Royal Duke demo: independent pressure diverged from the frozen operator view; restoration awaits duty plant operator approval.'},{id:'demo_exec_02',name:'database-failover',status:'SIMULATED APPROVAL',node:'promote_replica_to_primary',progress:48,tone:'warn',detail:'Demonstration data only; approval submission is disabled.'}];
const demoEvents:AuditEvent[]=[['14:32:08','DEMO','verify_job_completion','Simulated postcondition'],['14:31:52','DEMO','retry_job','Simulated Action Grant'],['14:30:17','DEMO','promote_replica','Simulated approval gate']];
const emptyMeta:Meta={data_mode:'OFFLINE',control_status:'UNREACHABLE',checked_at:'',fresh_until:'',benchmark:{status:'NO_CURRENT_EVIDENCE'}};
export function App(){ const[tab,setTab]=useState<Tab>('overview');const[meta,setMeta]=useState<Meta>(emptyMeta);const[executions,setExecutions]=useState<Execution[]>([]);const[events,setEvents]=useState<AuditEvent[]>([]);const[notice,setNotice]=useState('');
  useEffect(()=>{ let active=true; void fetch('/api/meta',{cache:'no-store'}).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<Meta>;}).then(async value=>{if(!active)return;setMeta(value);if(value.data_mode==='DEMO'){setExecutions(demoExecutions);setEvents(demoEvents);return;}if(value.data_mode!=='LIVE'){setExecutions([]);setEvents([]);return;}const listing=await fetch('/api/executions',{cache:'no-store'});if(!listing.ok)throw new Error();const body=await listing.json() as {executions?:Array<{execution_id:string;status:string;cursor?:{active_tokens?:{main?:{node_id:string}}};runbook?:{id:string}}>};const mapped=(body.executions??[]).map(execution=>({id:execution.execution_id,name:execution.runbook?.id??'execution',status:execution.status,node:execution.cursor?.active_tokens?.main?.node_id??'—',progress:execution.status==='COMPLETED'?100:50,tone:execution.status.includes('HALT')||execution.status.includes('APPROVAL')?'warn' as const:'good' as const,detail:'Current Control Plane state.'}));if(active)setExecutions(mapped);}).catch(()=>{if(active){setMeta(emptyMeta);setExecutions([]);setEvents([]);}});return()=>{active=false;};},[]);
  const badge=meta.benchmark.status;const modeLabel=meta.data_mode==='LIVE'?'LIVE · AUTHENTICATED':meta.data_mode==='DEMO'?'DEMO DATA · NO ACTIONS':'OFFLINE · NO CURRENT EVIDENCE';
  async function decide(decision:'APPROVE'|'REJECT'){if(meta.data_mode!=='LIVE'){setNotice('Demo and offline modes cannot submit approvals.');return;}setNotice('Submitting…');const response=await fetch('/api/approvals/current/decisions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision})});setNotice(response.ok?'Decision recorded by Authority.':`Decision rejected (${response.status}).`);}
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">RB</span><div><strong>RunbookBench</strong><span>operator console</span></div></div><div className="topbar-meta"><span className="live-dot"/> {modeLabel}</div></header><main className="workspace">
    <section className="intro"><div><p className="eyebrow">RUNBOOK COMPILER · RBIR v0.1</p><h1>Operational control, with authority visible.</h1><p className="intro-copy">Claims shown here come from server-verified current evidence.</p></div><div className={`safety-card ${badge==='PASS'?'':'evidence-missing'}`}><span className="shield">{badge==='PASS'?'✓':'!'}</span><div><small>FATAL SAFETY GATE</small><strong>{badge}</strong><span>{meta.benchmark.report_sha256?.slice(0,22)??'No verified report digest'}</span></div></div></section>
    <nav className="tabs" aria-label="Console sections">{([['overview','DAG overview'],['approvals','Approvals'],['lint','Diagnostic linter']] as Array<[Tab,string]>).map(([id,label])=><button key={id} className={tab===id?'tab active':'tab'} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==='overview'&&<><section className="section-heading"><div><p className="eyebrow">{meta.data_mode==='LIVE'?'CURRENT EXECUTIONS':'EXECUTION EVIDENCE'}</p><h2>Active DAG status</h2></div><span className="refresh">{modeLabel} · {executions.length} executions</span></section>{executions.length?<section className="execution-grid">{executions.map(execution=><article className="panel execution" key={execution.id}><div className="panel-head"><div><h3>{execution.name}</h3><code>{execution.id}</code></div><span className={`status ${execution.tone}`}>{execution.status}</span></div><div className="node-row"><span className="node-icon">{execution.tone==='warn'?'!':'↗'}</span><div><small>CURRENT NODE</small><strong>{execution.node}</strong></div></div><div className="progress"><span style={{width:`${execution.progress}%`}}/></div><p className="detail">{execution.detail}</p></article>)}</section>:<article className="panel empty-state"><h2>No current execution evidence</h2><p>Control is unavailable or returned no active executions.</p></article>}<section className="lower-grid"><article className="panel event-panel"><div className="panel-head"><div><p className="eyebrow">{meta.data_mode==='LIVE'?'CURRENT STREAM':'EVIDENCE STREAM'}</p><h2>Audit events</h2></div><span className="live-label">{meta.data_mode}</span></div><div className="events">{events.length?events.map(([time,kind,node,message])=><div className="event" key={`${time}-${node}`}><time>{time}</time><span className="event-kind audit">{kind}</span><div><strong>{node}</strong><p>{message}</p></div></div>):<p className="detail">No current event evidence.</p>}</div></article><article className="panel invariant"><p className="eyebrow">CURRENT EVIDENCE</p><div className="invariant-line"><span>Control</span><strong>{meta.control_status}</strong></div><div className="invariant-line"><span>Benchmark</span><strong>{badge}</strong></div><div className="invariant-line"><span>Checked</span><code>{meta.checked_at||'—'}</code></div></article></section></>}
    {tab==='approvals'&&<section className="approval-layout"><article className="panel approval-card"><p className="eyebrow">AUTHORITY DECISION</p><h2>{meta.data_mode==='LIVE'?'Pending actions are loaded from Authority':'No actionable approval evidence'}</h2><p className="detail">{meta.data_mode==='DEMO'?'Demo approval controls are intentionally disabled.':meta.data_mode==='OFFLINE'?'Authority is unavailable; no decision can be submitted.':meta.benchmark.status!=='PASS'?'Current benchmark evidence is not passing; decisions are disabled.':'Select a server-returned pending approval to act.'}</p><p role="status">{notice}</p><div className="actions"><button className="button danger" disabled={meta.data_mode!=='LIVE'||meta.benchmark.status!=='PASS'} onClick={()=>void decide('REJECT')}>Reject</button><button className="button primary" disabled={meta.data_mode!=='LIVE'||meta.benchmark.status!=='PASS'} onClick={()=>void decide('APPROVE')}>Sign &amp; approve</button></div></article></section>}
    {tab==='lint'&&<section className="lint-layout"><article className="panel linter"><p className="eyebrow">COMPILER DIAGNOSTICS</p><h2>{meta.data_mode==='DEMO'?'Demonstration diagnostics':'No current diagnostic artifact'}</h2><p className="detail">Diagnostics appear only when returned by the authenticated server with an artifact digest.</p></article></section>}
  </main></div>;}
