import { createReadStream, existsSync, readFileSync, statSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createServer } from 'node:http';
import { extname, join, normalize } from 'node:path';
import { GoogleAuth } from 'google-auth-library';
import { buildMeta } from './meta.mjs';
const port=Number(process.env.PORT||8080); const root=join(process.cwd(),'dist'); const mime={'.css':'text/css; charset=utf-8','.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
const controlUrl=process.env.CONTROL_URL??''; const authorityUrl=process.env.AUTHORITY_URL??''; const configuredMode=process.env.CONSOLE_DATA_MODE??'DEMO';
async function serviceHeaders(audience){ if(!audience||process.env.GOOGLE_APPLICATION_CREDENTIALS==='local') return {}; return new GoogleAuth().getIdTokenClient(audience).then((client)=>client.getRequestHeaders(audience)); }
async function controlReachable(){ if(!controlUrl) return false; try{ const headers=await serviceHeaders(controlUrl); const response=await fetch(`${controlUrl}/health`,{headers,signal:AbortSignal.timeout(3000)}); return response.ok; }catch{return false;} }
function loadReport(){ const path=process.env.BENCHMARK_REPORT_PATH; if(!path||!existsSync(path)) return undefined; try{const bytes=readFileSync(path);const report=JSON.parse(bytes.toString('utf8'));Object.defineProperty(report,'__file_sha256',{value:`sha256:${createHash('sha256').update(bytes).digest('hex')}`,enumerable:false});return report;}catch{return undefined;} }
async function readBody(request){ const chunks=[]; let size=0; for await(const chunk of request){ const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk); size+=value.length; if(size>1_048_576) throw new Error('REQUEST_BODY_TOO_LARGE'); chunks.push(value); } return Buffer.concat(chunks); }
async function proxy(request,response,targetBase,path){ try{ const iapJwt=String(request.headers['x-goog-iap-jwt-assertion']??''); if(!iapJwt){ response.writeHead(401,{'content-type':'application/json'}); response.end(JSON.stringify({error:'IAP_ASSERTION_REQUIRED'})); return; } const headers=await serviceHeaders(targetBase); const body=request.method==='GET'||request.method==='HEAD'?undefined:await readBody(request); const upstream=await fetch(`${targetBase}${path}`,{method:request.method,headers:{...headers,'content-type':String(request.headers['content-type']??'application/json'),'x-runbook-iap-jwt':iapJwt},body,redirect:'manual'}); response.writeHead(upstream.status,{'content-type':upstream.headers.get('content-type')??'application/json','cache-control':'no-store'}); response.end(Buffer.from(await upstream.arrayBuffer())); }catch(error){ const tooLarge=error instanceof Error&&error.message==='REQUEST_BODY_TOO_LARGE'; response.writeHead(tooLarge?413:502,{'content-type':'application/json'}); response.end(JSON.stringify({error:tooLarge?'REQUEST_BODY_TOO_LARGE':'UPSTREAM_UNAVAILABLE'})); } }
createServer(async(request,response)=>{ const url=new URL(request.url||'/','http://localhost');
  if(request.method==='GET'&&url.pathname==='/api/meta'){ const meta=buildMeta({configuredMode,iapJwt:String(request.headers['x-goog-iap-jwt-assertion']??''),controlReachable:await controlReachable(),report:loadReport(),expectedReportDigest:process.env.BENCHMARK_REPORT_SHA256}); response.writeHead(200,{'content-type':'application/json','cache-control':'no-store'}); response.end(JSON.stringify(meta)); return; }
  if(url.pathname.startsWith('/api/approvals/')&&url.pathname.endsWith('/decisions')&&authorityUrl){ await proxy(request,response,authorityUrl,url.pathname.slice(4)); return; }
  if(url.pathname.startsWith('/api/')&&controlUrl){ await proxy(request,response,controlUrl,url.pathname.slice(4)); return; }
  let path; try{path=normalize(decodeURIComponent(url.pathname)).replace(/^(\.\.[/\\])+/,'');}catch{response.writeHead(400,{'content-type':'text/plain','x-content-type-options':'nosniff'});response.end('Bad Request');return;}
  let target=join(root,path==='/'?'index.html':path); if(!target.startsWith(root)||!existsSync(target)||statSync(target).isDirectory()) target=join(root,'index.html'); response.writeHead(200,{'content-type':mime[extname(target)]||'application/octet-stream','cache-control':target.endsWith('index.html')?'no-cache':'public, max-age=31536000, immutable','content-security-policy':"default-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; script-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'",'permissions-policy':'camera=(), microphone=(), geolocation=()','referrer-policy':'no-referrer','x-content-type-options':'nosniff'}); createReadStream(target).pipe(response);
}).listen(port,()=>console.log(`[rb-console] listening on ${port} (${configuredMode})`));
